version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - certbot
      - adminer
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - mix_net
      - default
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    networks:
      - nginx_net
      - deafault
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - mix_net
      - default
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:latest
    restart: always
    depends_on:
      - db
    networks:
      - mix_net
      - db_net
    expose:
      - 8080

  frontend:
    build: ./lk-mixflowers-frontend
    container_name: mix_front
    hostname: mix_front
    networks:
      - default
      - mix_net
    expose:
      - 5000
    depends_on:
      - backend
    restart: always

  backend:
    build: ./lk-mixflowers-backend
    container_name: mix_back
    hostname: mix_back
    env_file:
      - env/backend.env
    restart: always
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - default
      - mix_net
      - db_net

  db:
    container_name: mix_db
    image: postgres:latest
    hostname: mix_db
    env_file:
      - env/mix_db.env
    volumes:
      - ./data/redmine_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    expose:
      - 5432
    networks:
     - db_net

networks:
  mix_net:
    name: mix_net
    internal: true
  db_net:
    name: db_net
    internal: true
